//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _5Bites.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeLocations = new HashSet<EmployeeLocation>();
            this.EmployeeStores = new HashSet<EmployeeStore>();
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public byte[] Password { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual ICollection<EmployeeLocation> EmployeeLocations { get; set; }
        public virtual ICollection<EmployeeStore> EmployeeStores { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
